[package]
name = "dora-ir"
version = "0.1.0"
edition = "2021"

[dependencies]
melior = { version = "0.18.6", features = [
    "ods-dialects",
] }
mlir-sys = "0.2.2"

[dev-dependencies]
insta = "1.39.0"
